import localFont from "next/font/local";
import "./globals.css";

const getAudioWideRegular = localFont({
  src: './font/Audiowide-Regular.ttf',
  variable: "--font-audiowide"

});

const getGoogleSansFlex = localFont({
  src: './font/GoogleSansFlex.ttf',
  variable: "--font-google-sans-flex"
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${getAudioWideRegular.variable} ${getGoogleSansFlex.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
